# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://recon-malta-2018.netlify.com/"
languageCode = "en-AU"
title = "RECON and EAN workshop: R for outbreak analytics"

# Metadata
[params]
  author = "Thibaut Jombart & Amrish Baidjoe"
  description = "Website for the RECON and EAN R for outbreak analytics workshop, Malta, 19-20 November 2018"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/malta_edit.jpeg"
  title = "Introduction to outbreak analysis using R"
  description = "/// Short course on outbreak analytics organised by RECON and EAN<br>/// Malta, Mater Dei Hospital, 19-20 November 2018"

# Navigation section
[params.nav]
  services = "Agenda"
  mission = "Practical info"
  team = "Organisers"
  contact = "Register"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Services section
[params.services]
  enable = true
  video = false
  vidlink = ""
  title = "Agenda"
  description = "<p>This two-days short course, co-organised by the R Epidemics Consortium (<a href='http://www.repidemicsconsortium.org/'>RECON</a>) and the EPIET Alumni Network (<a href='http://epietalumni.net'>EAN</a>), will provide an introduction to outbreak analysis using the R software. It will take place in the <a href='https://goo.gl/maps/fvyXk52TuQ22'>Mater Dei Hospital</a> Malta, 19-20 March 2018, as a satellite event to the <a href='https://www.escaide.eu/en'>ESCAIDE</a> conference. The workshop will be aimed at people currently undertaking, or having recently completed, a field-epidemiology training programme (FETP), with some interest in epidemics analysis using R. Participants will get an overview and gain practical experience of new packages for outbreak analysis developed by <a href='http://www.repidemicsconsortium.org/'>RECON</a>, including descriptive approaches (epicurves), short-term forecasting, or automated sitrep generation. While the course will be pitched at a beginner level, we strongly recommend that participants revise R basics by completing the free introduction session provided on <a href='https://www.datacamp.com/courses/free-introduction-to-r'>Datacamp</a>. Applications should be sent using the providing form (see 'Register' tab above).</p>"
  # [[params.services.item]]
  #   icon = "icon-present"
  #   title = "Web Development"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  # [[params.services.item]]
  #  icon = ""
  #  title = "Registration"
  #  description = "<p><b>Thursday 22nd March 2018 <br>9:00 - 9:30</b></p><p>Welcoming the participants, coffee.</p>"

  #  [[params.services.item]]
  #   icon = ""
  #  title = "Symposium"
  # description = "<p><b>Thursday 22nd March 2018 <br>9:30 - 17:00</b></p><p>The programme is available <a href='https://recon-gathering-march2018.netlify.com/files/programme.pdf'>here</a>. </p>"

  # [[params.services.item]]
  #  icon = ""
  #  title = "Social event"
  #  description = "<p><b>Thursday 22nd March 2018 <br> 17:30 - 23:00</b></p><p>Reception at the bar of the hotel, followed by dinner.</p>"

  # [[params.services.item]]
  #  icon = ""
  #  title = "Parallel session 1"
  #  description = "<p><b>Friday 23rd March 2018 <br>9:30 - 16:00</b></p><p>Working group on resources for field epidemiology training.</p>"

  # [[params.services.item]]
  #  icon = ""
  #  title = "Parallel session 2"
  #  description = "<p><b>Friday 23rd March 2018 <br>9:30 - 16:00</b></p><p>Community-driven hackathon. Click <a href='https://github.com/RECON-gathering-March-2018/projects'>here</a> to discuss existing projects or propose new ones.</p>"

  # [[params.services.item]]
  #  icon = ""
  #  title = "Conclusion"
  #  description = "<p><b>Friday 23rd March 2018 <br>16:00 - 16:30</b></p><p>Debriefing of parallel sessions and concluding remarks.</p>"

# Mission section
[params.mission]
  enable = true

  # [params.mission.images]
  #   enable = true

  #   [[params.mission.images.list]]
  #     img = "images/compass.jpg"
  #   [[params.mission.images.list]]
  #     img = "images/img_4.jpg"
  #   [[params.mission.images.list]]
  #     img = "images/img_1.jpg"
  #   [[params.mission.images.list]]
  #     img = "images/calendar.jpg"

  [[params.mission.item]]
    weight = 1
    name = "location"
    title = "Location"
    subtitle = 'The workshop will be hosted at the Mater Dei Hospital, Malta'
    description = '<p>Here is a map of the location:<br>"<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3231.845674352555!2d14.474202051114345!3d35.90179518004605!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x130e45548ca6d317%3A0x9af354451a8f887d!2sMater+Dei+Hospital!5e0!3m2!1sen!2suk!4v1531152876216" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>"</iframe></p>'

  [[params.mission.item]]
    weight = 2
    name = "date"
    title = "Date"
    subtitle = "The event will take place accross two days, Monday the 19th - and Tuesday the 20th of November 2018, exact times will be announced closer to the event."
    description = ""

  [[params.mission.item]]
    weight = 3
    name = "register"
    title = "Register"
    subtitle = ""
    description = '<p>Please use the google form below to apply, or follow <a href="https://goo.gl/forms/q4JPcu8c1BMmInN63">this link</a> to open the form in a new page. Attendance will depend on availability and will be confirmed at a later stage. As soon as participation slots are full, new applicants will be added to a reserve list. </p><p><iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeDjxHZShQvjplazC-qM_uN2PKOF9akCAkCS7nQujh2wkrLZA/viewform?embedded=true" width="100%" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe></p>'
 
  [[params.mission.item]]
    weight = 4
    name = "contact"
    title = "Contact"
    subtitle = "For more information, use the contact details provided below, for question regarding registration, e-mail EAN."
    description = "Organisation: <p><ul><li><a href='mailto:eanboard@gmail.com'>EAN Board</a><li><a href='mailto:amrish.baidjoe@gmail.com'>Amrish Baidjoe</a><li><a href='mailto:thibautjombart@gmail.com'>Thibaut Jombart</a></ul></p>"


  [[params.mission.item]]
    weight = 5
    name = "programme"
    title = "Programme"
    subtitle = "What is on the menu?"
    description = "The final programme of the short course will be published on this website soon. Upon registration, applicants are asked for their preferences in terms of content out of: R basics, epidemic curves, estimation of transmissibility, short-term incidence forecasting, GIS, automated report generation."


# [[params.mission.item]]
#     weight = 6
#     name = "presentations"
#     title = "Presentations"
#     subtitle = "Slides of some of the presentations of the event"
#     description = "<p>Introduction<ul><li><a href='https://recon-gathering-march2018.netlify.com/files/intro-thibaut-jombart.pdf'>Introduction: challenges and opportunities in outbreak response analytics</a> (Thibaut Jombart, ICL)</li><li><a href='https://recon-gathering-march2018.netlify.com/files/plenary-oliver-morgan.pptx'>Plenary: decision making in public health emergencies</a> (Oliver Morgan, WHO)</li></ul></p><p>Talks<ul><li><a href='https://recon-gathering-march2018.netlify.com/files/talk-iro-evlampidou.pdf'>Data collection and analysis during mass displacements: the MSF experience in the Balkans during the 2015 refugee crisis</a> (Iro Evlampidou, MSF)</li><li><a href='https://recon-gathering-march2018.netlify.com/files/talk-jonathan-polonsky.pdf'>Diphtheria outbreak among Rohingya refugees, Bangladesh 2017-18</a> (Jonathan Polonsky, WHO)</li><li><a href='https://recon-gathering-march2018.netlify.com/files/talk-anne-cori.pdf'>Mathematical modelling and outbreak response: lessons learnt from West African Ebola</a> (Anne Cori, ICL)</li><li><a href='https://recon-gathering-march2018.netlify.com/files/talk-sebastian-funk.pdf'>Real-time modelling and forecasting during infectious disease outbreaks</a> (Sebastian Funk, LSHTM)</li><li><a href='https://recon-gathering-march2018.netlify.com/files/talk-gregory-armstrong.pptx'>Nucleotide sequencing in outbreak detection and response</a> (Gregory Armstrong, US CDC)</li>

# <li><a href='https://recon-gathering-march2018.netlify.com/files/talk-jimmy-whitworth.pptx'>Transition to R: pros and cons from an EU FETP perspective</a> (Jimmy Withworth, LSHTM)</li>

# <li><a href='https://recon-gathering-march2018.netlify.com/files/intro-amrish-baidjoe.pptx'>Current challenges with data analyses tools and training for field-epidemiologists</a> (Amrish Baidjoe, ICL)</li>

# <li><a href='https://recon-gathering-march2018.netlify.com/files/talk-irina-czogiel.pptx'>Transition to R: pros and cons from an EU FETP perspective</a> (Irina Czogiel, RKI)</li><li><a href='https://recon-gathering-march2018.netlify.com/files/talk-lisa-hansen.pdf'>Anthropology for epidemiologists: qualitative methods in public health investigations</a> (Lisa Hansen, RIVM / ECDC)</li><li><a href='https://recon-gathering-march2018.netlify.com/files/talk-renee-anne-christensen.pdf'>The GOARN training programme</a> (Renee Anne Christensen, GOARN)</li></ul></p>"






  # [[params.mission.item]]
  #   weight = 5
  #   name = "scholarships"
  #   title = "Scholarships"
  #   subtitle = "If you need financial support for travel and accommodation to attend the course, you can apply to a scholarship for this course. See the relevant section in the registration form (see 'register' section)."
  #   description = ""



 

# # Work section
# [params.work]
#   enable = false

#   [[params.work.item]]
#     title = "Consectetur adipisicing"
#     subtitle = "Web Design"
#     img = "images/img_1.jpg"

#   [[params.work.item]]
#     title = "Consectetur adipisicing"
#     subtitle = "Web Design"
#     img = "images/img_2.jpg"

#   [[params.work.item]]
#     title = "Consectetur adipisicing"
#     subtitle = "Web Design"
#     img = "images/img_3.jpg"

# Team section
[params.team]
  enable = true
  title = "Organisers"
  description = "Organising members and facilitators"

  [[params.team.item]]
    name = "Thibaut Jombart"
    position = "Associate Professor, London School of Hygiene and Tropical Medicine / Imperial College London, UK"
    description = "Outbreak response analytics and head of RECON.<br>"
    img = "images/thibaut.jpg"
    # dribbble = "#"
    github = "https://github.com/thibautjombart"
    twitter = "https://twitter.com/TeebzR"

  [[params.team.item]]
    name = "Amrish Baidjoe"
    position = "Research Associate, Imperial College London, UK"
    description = "Field epidemiologist/microbiologist and coordinator of RECON, president of the EPIET Alumni Network."
    img = "images/amrish.jpg"
    github = "https://github.com/AmmerB"
    twitter = "https://twitter.com/Ammer_B"

  [[params.team.item]]
    name = "Lieke van Alphen"
    position = "Molecular Medical Microbiologist, MUMC, NL"
    description = "Providing logistics support on behalf of EAN, EAN treasurer"
    img = "images/lieke.jpeg"

#add following members: facilitators, admin support, Chris Barbara

 
  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = false
  title = "Register"
  message = "Bla bla bla"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p>This event is organised by:<br><a href='http://www.repidemicsconsortium.org/'><img src='http://www.repidemicsconsortium.org/img/logo.png' width='300px' alt='R Epidemics Consortium'><br>the R Epidemics Consortium</a><br><large>&</large><br><a href='http://http://epietalumni.net/'><img src='images/ean.png' width='300px' alt='EPIET Alumni Network'><br>the EPIET Alumni Network</a></p><small>This event is co-funded by the Medical Research Council (MRC) Centre for Outbreak Analysis and Modelling, and the National Institute for Health Research - Health Protection Research Unit (NIHR-HPRU) for Modelling Methodology.</small></p><p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a>. Website by <a href='https://thibautjombart.netlify.com/'>Thibaut Jombart</a> and Amrish Baidjoe.</small></p>"
  github = "https://github.com/reconhub/course-malta-2018"
  
